pattern/direct-messaging-service/README.md
=> chore: update readme

prime/content/console.ts, service/diabetes-research-hub/ux.auto.sql
=> Fix: syntax error introduced by Baasit

pattern/infra-policies/stateless-ip.surveilr.sql, pattern/infra-policies/ux.sql.ts
This feature introduces the creation of a nested inner list within the Policy module. It includes the ability to manage detailed sub-lists for each policy item, providing more granular control and organization of policy data.
=> feat: policy inner list

pattern/infra-controls/README.md, pattern/infra-controls/deps.ts, pattern/infra-controls/orchestrate-stateful-ic.surveilr.sql, pattern/infra-controls/stateless-ic.surveilr.sql, pattern/infra-controls/ux.sql.ts, pattern/infra-policies/README.md, pattern/infra-policies/ux.sql.ts
=> feat: infra controls

pattern/infra-policies/README.md
=> Read me file update

pattern/direct-messaging-service/README.md, pattern/direct-messaging-service/assets/style.css, pattern/direct-messaging-service/stateless-dms.surveilr.sql, pattern/direct-messaging-service/ux.sql.ts
=> chore: update readme and CCDA detail page

pattern/infra-controls/ux.sql.ts
=> Link to control detail

pattern/direct-messaging-service/stateless-dms.surveilr.sql, pattern/direct-messaging-service/ux.auto.sql, pattern/direct-messaging-service/ux.sql.ts
=> chore: update code and add more views to the list

prime/web-ui-content/console.ts
This pull request refines the SQL script for managing the `sqlpage_aide_navigation` table to ensure idempotent operations while retaining necessary data and maintaining the table structure.
=> fix: idempotent issue in sqlpage_aide_navigation

pattern/info-assurance-controls/ux.sql.ts, pattern/info-assurance-policies/ux.sql.ts, pattern/infra-assurance/ux.sql.ts, pattern/infra-audit/ux.sql.ts, service/opsfolio/README.md, service/opsfolio/deps.ts, service/opsfolio/web-ui.sql.ts
This PR introduces a unified SQL page generator that consolidates the SQL content for all four sections: Info Assurance Controls, Info Assurance Policies, and Infra Assurance.
**Key Changes:**
- Code Imports: Imported SQL modules from the respective directories:
1. info-assurance-controls
2. info-assurance-policies
3. infra-assurance
- Unified SQL Generation: The SQL() function collects and merges SQL queries from all three modules and outputs them as a single unified SQL string.
- Output on Main Execution: If executed as a main module, the generated SQL is printed to the console.
=> feat: uniformed view

pattern/integration-engine/README.md
- introduction to the Integration Engine (IE) -Electronic Data Exchange Overview
-Features and use cases
-Technical Summary
-Various Use Cases and Sequence Diagrams
=> docs: update README with additional content

pattern/integration-engine/README.md
- update the Mermaid graph to fix the issue where some sub-graph elements are not displaying correctly due to caption length issues.
=> docs: update the mermaid graph

pattern/info-assurance/README.md, pattern/info-assurance/deps.ts, pattern/info-assurance/stateless-iat.surveilr.sql, pattern/info-assurance/ux.sql.ts, pattern/infra-assurance/stateless-ia.surveilr.sql, pattern/infra-assurance/ux.sql.ts, service/opsfolio/web-ui.sql.ts
This PR adds new views for Infrastructure Assurance and Information Assurance within the SQLite component.
=> feat: add infra and info assurance

pattern/integration-engine/README.md
- update README with RSIE content
=> docs: update README with RSIE content

assurance/ingest_direct_messages_test.ts, pattern/direct-messaging-service/ux.sql.ts
Added test for direct message service
=> chore: add direct message service test

pattern/info-assurance-policies/ux.sql.ts
**Added Evidence Tab Along with Policy Tab**: Introduced a new "Evidence" tab in the dashboard, allowing users to view and manage evidence alongside policies for more comprehensive information management.
=> refactor: info policy dashboard change

pattern/integration-engine/README.md
update README with additional content for RSIE
=> docs: update README with additional content for RSIE

pattern/info-assurance-policies/stateless-ip.surveilr.sql, pattern/info-assurance-policies/ux.sql.ts, pattern/infra-assurance/ux.sql.ts
This PR introduces a new SQL web page for the Infra Assurance Detail and enhances the existing information policies by incorporating more evidence.
=> Add SQL View for Infra Assurance Detail Page and Extend Information Policies with Additional Evidences

pattern/integration-engine/README.md
update the data storage section in the RSIE README
=> docs: update the data storage section in the RSIE README

assurance/info_assurance_controls_test.ts, assurance/info_assurance_policies_test.ts, pattern/info-assurance-controls/README.md, pattern/info-assurance-controls/stateless-ic.surveilr.sql, pattern/info-assurance-policies/README.md, pattern/info-assurance-policies/stateless-ip.surveilr.sql, pattern/info-assurance-policies/ux.sql.ts, pattern/infra-assurance/README.md
This PR introduces new test cases for validating policies and control views.
=> feat: added policies and controls test case

pattern/info-assurance-controls/info_assurance_controls_test.ts, pattern/info-assurance-policies/stateless-ip.surveilr.sql
-  **Expanded Evidence List**:
Additional evidence entries were added to the existing list, improving coverage and supporting documentation for various control policies.
- **New Test Cases for Control Regimes and Control Groups**:
Introduced test cases to validate control regimes and control groups, ensuring the accuracy and consistency of the implemented policies.
=> feat: added info policies evidence

pattern/info-assurance-controls/info_assurance_controls_test.ts, pattern/info-assurance-policies/stateless-ip.surveilr.sql
- **Control Views**:
Added test cases for control views to ensure the integrity and reliability of control-related data in the assurance process.
- **Policy Evidence**:
Additional evidence references were included in policies to support compliance requirements.
=> test: infra assurance test case

pattern/info-assurance-policies/stateless-ip.surveilr.sql, pattern/info-assurance/info_assurance_test.ts, pattern/infra-assurance/infra_assurance_test.ts, pattern/infra-assurance/stateless-ia.surveilr.sql, pattern/infra-audit/infra_audit_test.ts, pattern/infra-audit/stateless-ia.surveilr.sql
This PR introduces the integration of GitLab evidences into the policies section of our system.
=> feat: git lab evidence
